name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Checkout sources
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build with Maven
        run: mvn --batch-mode -Pjacoco verify

      - name: Broadcast update event
        if: github.ref == 'refs/heads/main'
        uses: gridsuite/broadcast-event@main
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          organizations: gridsuite
          event-type: ws_dependencies_updated
